trigger:
- main

pool:
  name: default  # Use self-hosted agent pool name here

steps:
# Maven build step, assuming JDK 11 is already installed and JAVA_HOME is set
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'
    jdkArchitectureOption: 'x64'  # Ensure that the correct architecture is specified
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
