---
- name: Deploy Maven Artifact
  hosts: local
  become: yes
  tasks:
    - name: Copy the artifact to the deployment directory
      copy:
        src: "/var/lib/jenkins/workspace/m/target/m-SNAPSHOT.jar"
        dest: "/opt/deployment/HelloMaven.jar"
