---
- name: Deploy Maven Artifact
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure the deployment directory exists
      file:
        path: /opt/deployment
        state: directory
        mode: '0755'

    - name: Copy the artifact to the deployment directory
      copy:
        src: "/var/lib/jenkins/workspace/j/target/HelloMaven-1.0-SNAPSHOT.jar"
        dest: "/opt/deployment/HelloMaven.jar"
        mode: '0644'
